name: CI
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Format
        run: bun x prettier --check .
      - name: Lint
        run: bun run lint
      - name: Generate Migration
        run: bun run db:generate
      - name: Migrate Database
        run: bun run db:migrate
      - name: Seed Database
        run: bun run db:seed
